version: "2"

build:
  os: "ubuntu-lts-latest"  # or you can use "ubuntu-20.04", "ubuntu-22.04", or "ubuntu-24.04"
  tools:
    java: 
      version: "20"

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
